title: Personal URL Shortener / Redirector
description: âœ‚ï¸ğŸ”— This repo contains all the urls that i like to redirect.
show_downloads: false
timezone: Asia/Kolkata
google_analytics: UA-63845590-5
theme: jekyll-theme-cayman
permalink: /:slug/
plugins:
  - jekyll-redirect-from