title: Personal URL shortener
description: âœ‚ï¸ğŸ”— This repo contains all the urls that i like to redirect.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
permalink: /:slug/
plugins:
  - jekyll-redirect-from