name: On Push

on:
  schedule:
    - cron: '*/60 * * * *'
  push:
    branches:
      - master

jobs:
  Dynamic_Links:
    runs-on: ubuntu-latest
    steps:
      - name: ğŸ“© Fetching Repository
        uses: actions/checkout@v2
      - name: ğŸ’½ Installing PHP
        uses: nanasess/setup-php@master
        with:
          php-version: '7.2'
      - name: âš’ï¸Generating Envato Links
        run: |
          php .github/custom-scripts/envato.php
      - name: âš’ï¸Generating WordPress Links
        run: |
          php .github/custom-scripts/wordpress.php
      - name: ğŸš€ Publishing To Github
        run: |
          git config --global user.email "githubactionbot+envato@gmail.com" && git config --global user.name "Envato Items Links Updated !"
          if [ "$(git status ./envato/ --porcelain)" != "" ]; then
            echo "ğŸ‘Œ Envato Items Link Updated"
            git add ./envato/.
            git commit -m "ğŸ“– #$GITHUB_RUN_NUMBER - Envato Items Link Updated / âš¡ Triggered By $GITHUB_SHA"
            git push origin
          else
            echo "âœ… Nothing To Create"
          fi

          git config --global user.email "githubactionbot+wp@gmail.com" && git config --global user.name "WordPress Plugins Links Updated !"
          if [ "$(git status ./envato/ --porcelain)" != "" ]; then
            echo "ğŸ‘Œ WordPress Plugins Link Updated"
            git add ./wp/.
            git commit -m "ğŸ“– #$GITHUB_RUN_NUMBER - WordPress Plugins Link Updated / âš¡ Triggered By $GITHUB_SHA"
            git push origin
          else
            echo "âœ… Nothing To Create"
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
